
((digest . "4637dfcc85484581eb754d490baaa785") (undo-list (1 . 3707) ("((last-sort-comparer
  (bmkp-info-cp bmkp-gnus-cp bmkp-url-cp bmkp-local-file-type-cp)
  bmkp-alpha-p)
 (last-reverse-sort-p)
 (last-reverse-multi-sort-p)
 (last-latest-bookmark-alist #1=(#(\"cmaes\" 0 5
				   (bmkp-full-record #1#))
				 (buffer-name . \"cmaes\")
				 (front-context-string . \"CMAEvolutionStra\")
				 (rear-context-string . \"416 11-18 16:45 \")
				 (front-context-region-string)
				 (rear-context-region-string)
				 (visits . 1)
				 (time 22286 25280 495921 200000)
				 (created 22281 6493 896307 900000)
				 (position . 285)
				 (filename . #2=\"c:/Users/fukumoto/workspace/CMA_ES/src/fr/inria/optimization/cmaes/\")
				 (dired-directory . #2#)
				 (dired-marked)
				 (dired-switches . \"-al\")
				 (dired-subdirs)
				 (dired-hidden-dirs)
				 (handler . bmkp-jump-dired))
			     #3=(#13=#(\"favorite_music.org\" 0 18
				       (bmkp-full-record #3#))
				     (filename . \"c:/Users/fukumoto/Dropbox/org/favorite_music/favorite_music.org\")
				     (buffer-name . \"favorite_music.org\")
				     (front-context-string . \"\\n- [ ] h.b.s | さ\")
				     (rear-context-string . \"TITLE: 良曲\\n\\n* 良曲\\n\")
				     (front-context-region-string)
				     (rear-context-region-string)
				     (visits . 2)
				     (time 22284 60826 909170 700000)
				     (created 22280 65365 183331 100000)
				     (position . 79))
			     #4=(#(\"todo.org\" 0 8
				   (bmkp-full-record #4#))
				 (filename . #5=\"c:/Users/fukumoto/Dropbox/org/TODO/TODO.org\")
				 (buffer-name . #5#)
				 (front-context-string . \"\\n** TODO undo-tr\")
				 (rear-context-string . \"E: TODO\\n\\n* emacs\")
				 (front-context-region-string)
				 (rear-context-region-string)
				 (visits . 2)
				 (time 22281 376 957745 200000)
				 (created 22280 64971 226226 800000)
				 (position . 83))
			     #6=(#(\"memo.org\" 0 8
				   (bmkp-full-record #6#))
				 (filename . #7=\"c:/Users/fukumoto/Dropbox/org/memo.org\")
				 (buffer-name . #7#)
				 (front-context-string . \"* memo          \")
				 (rear-context-string)
				 (front-context-region-string)
				 (rear-context-region-string)
				 (visits . 2)
				 (time 22281 8225 642147 300000)
				 (created 22280 64927 450893 600000)
				 (position . 1))
			     #8=(#(\"org-directory\" 0 13
				   (bmkp-full-record #8#))
				 (tags)
				 (buffer-name . #9=\"c:/Users/fukumoto/Dropbox/org/\")
				 (front-context-string . \"TODO\\n  drwxrwxrw\")
				 (rear-context-string . \"096 04-09 21:44 \")
				 (front-context-region-string)
				 (rear-context-region-string)
				 (visits . 5)
				 (time 22287 8834 938634 600000)
				 (created 22280 64846 498076 100000)
				 (position . 244)
				 (filename . #9#)
				 (dired-directory . #9#)
				 (dired-marked)
				 (dired-switches . \"-al\")
				 (dired-subdirs)
				 (dired-hidden-dirs)
				 (handler . bmkp-jump-dired))
			     #10=(#(\"org-capture-last-stored\" 0 23
				    (bmkp-full-record #10#))
				  (annotation)
				  (tags)
				  (filename . \"c:/Users/fukumoto/Dropbox/org/TODO/TODO.org\")
				  (buffer-name . \"TODO.org\")
				  (front-context-string . \"** TODO 新入生歓迎会の出\")
				  (rear-context-string . \"f9eea1bcb\\n:END:\\n\")
				  (front-context-region-string)
				  (rear-context-region-string)
				  (visits . 0)
				  (time . #11=(22284 28222 672987 600000))
				  (created . #11#)
				  (position . 2498)))
 (last-bmenu-omitted-bookmarks)
 (last-bmenu-marked-bookmarks)
 (last-bmenu-filter-function)
 (last-bmenu-filter-pattern . #12=\"\")
 (last-bmenu-title . #12#)
 (last-bmenu-bookmark . #13#)
 (last-specific-buffer . #12#)
 (last-specific-file . #12#)
 (last-bmenu-toggle-filenames . t)
 (last-bmenu-before-hide-marked-alist)
 (last-bmenu-before-hide-unmarked-alist)
 (last-bookmark-file . \"c:\\\\Users\\\\fukumoto\\\\home\\\\.emacs.d\\\\bookmarks\"))
" . 1) (t 22287 37607 0 0) (1 . 3712) ("((last-sort-comparer
  (bmkp-info-cp bmkp-gnus-cp bmkp-url-cp bmkp-local-file-type-cp)
  bmkp-alpha-p)
 (last-reverse-sort-p)
 (last-reverse-multi-sort-p)
 (last-latest-bookmark-alist #1=(#(\"favorite_music.org\" 0 18
				   (bmkp-full-record #1#))
				 (filename . \"c:/Users/fukumoto/Dropbox/org/favorite_music/favorite_music.org\")
				 (buffer-name . \"favorite_music.org\")
				 (front-context-string . \"\\n- [ ] h.b.s | さ\")
				 (rear-context-string . \"TITLE: 良曲\\n\\n* 良曲\\n\")
				 (front-context-region-string)
				 (rear-context-region-string)
				 (visits . 0)
				 (time . #2=(22280 65365 183331 100000))
				 (created . #2#)
				 (position . 79))
			     #3=(#(\"todo.org\" 0 8
				   (bmkp-full-record #3#))
				 (filename . #4=\"c:/Users/fukumoto/Dropbox/org/TODO/TODO.org\")
				 (buffer-name . #4#)
				 (front-context-string . \"\\n** TODO undo-tr\")
				 (rear-context-string . \"E: TODO\\n\\n* emacs\")
				 (front-context-region-string)
				 (rear-context-region-string)
				 (visits . 2)
				 (time 22281 376 957745 200000)
				 (created 22280 64971 226226 800000)
				 (position . 83))
			     #5=(#(\"memo.org\" 0 8
				   (bmkp-full-record #5#))
				 (filename . #6=\"c:/Users/fukumoto/Dropbox/org/memo.org\")
				 (buffer-name . #6#)
				 (front-context-string . \"* memo          \")
				 (rear-context-string)
				 (front-context-region-string)
				 (rear-context-region-string)
				 (visits . 2)
				 (time 22281 8225 642147 300000)
				 (created 22280 64927 450893 600000)
				 (position . 1))
			     #7=(#(\"org-directory\" 0 13
				   (bmkp-full-record #7#))
				 (tags)
				 (buffer-name . #8=\"c:/Users/fukumoto/Dropbox/org/\")
				 (front-context-string . \"TODO\\n  drwxrwxrw\")
				 (rear-context-string . \"096 04-09 21:44 \")
				 (front-context-region-string)
				 (rear-context-region-string)
				 (visits . 4)
				 (time 22280 65476 92262 400000)
				 (created 22280 64846 498076 100000)
				 (position . 244)
				 (filename . #8#)
				 (dired-directory . #8#)
				 (dired-marked)
				 (dired-switches . \"-al\")
				 (dired-subdirs)
				 (dired-hidden-dirs)
				 (handler . bmkp-jump-dired))
			     #9=(#(\"org-capture-last-stored\" 0 23
				   (bmkp-full-record #9#))
				 (annotation)
				 (tags)
				 (filename . #4#)
				 (buffer-name . \"TODO.org\")
				 (front-context-string . \"** TODO or-agend\")
				 (rear-context-string . \"OS 規定のプログラムから開く\\n\")
				 (front-context-region-string)
				 (rear-context-region-string)
				 (visits . 0)
				 (time . #10=(22281 325 21630 700000))
				 (created . #10#)
				 (position . 1818)))
 (last-bmenu-omitted-bookmarks)
 (last-bmenu-marked-bookmarks)
 (last-bmenu-filter-function)
 (last-bmenu-filter-pattern . #11=\"\")
 (last-bmenu-title . #11#)
 (last-bmenu-bookmark)
 (last-specific-buffer . #11#)
 (last-specific-file . #11#)
 (last-bmenu-toggle-filenames . t)
 (last-bmenu-before-hide-marked-alist)
 (last-bmenu-before-hide-unmarked-alist)
 (last-bookmark-file . \"c:\\\\Users\\\\fukumoto\\\\home\\\\.emacs.d\\\\bookmarks\"))
" . 1) (t 22281 57990 0 0)))
